/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This interface was referenced by `undefined`'s JSON-Schema
 * via the `definition` "Elections".
 */
export type Elections = Election[];

/**
 * This interface was referenced by `undefined`'s JSON-Schema
 * via the `definition` "Election".
 */
export interface Election {
  title: string;
  sub_elections?: SubElection[];
  slug: string;
}
/**
 * This interface was referenced by `undefined`'s JSON-Schema
 * via the `definition` "SubElection".
 */
export interface SubElection {
  title: string;
  slug: string;
}
